### ISSUE TITLE
Add Share button to User's Public profile

### ISSUE THREAD

**Issue by khmak3** [OurLandHK/WebApp#139]
This link should be <base URL>/?userid=<user.uid>
example https://ourland.hk/?userid=Q72z8i9yHyaLCCiAyR5BoGd0kQr1

**Comment by khmak3** [comment]
It shoud be refactor from the ShareDrawer by put text/url/hash tag

**Comment by wingkwong** [comment]
What are the expected m and hashtag values?

**Comment by khmak3** [comment]
hashtag should be 我地
m should be Username. 
Since we will support proper metadat in #37. Some just m and hashtsga should be fine
