### ISSUE TITLE
Notification by email

### ISSUE THREAD

**Issue by khmak3** [OurLandHK/WebApp#212]
1. User can provide notifical email
2. Any event related to user (nearby address, concern, created by) should receive email for any update.

**Comment by wingkwong** [comment]
if a user updates its own post, should the email also be sent to his/her email address?

**Comment by khmak3** [comment]
Following case should be send to his/her email address
1. The post update in his/her home&office address
2. The post create by user
3. The user involve (add comment) for the post
4. The user mark concern for the post

Each user should receive email for once

On the other hand ,if the user updates its own post. I believe they don't mail receive mail.
But it should be good idea for record user who updated the post.

So, we may need to change the message record's scheme to enable this

**Comment by khmak3** [comment]
For the notification rule , user other issue to keep check
