### ISSUE TITLE
Use marker on map to adjust geolocation after user input

### ISSUE THREAD

**Issue by khmak3** [OurLandHK/WebApp#233]
After user input the location from get gps or street address.  The map will show in the location button.  User can drag the marker to adjust. Location

**Comment by fionnachan** [comment]
fyi i changed the google maps package because the previous one didnt adapt the full google maps API
please also install the recompose package.

https://tomchentw.github.io/react-google-maps/

**Comment by calendarw** [comment]
= TODO
Replace marker with fake-marker
http://alizahid.net/post/172622558271/keep-marker-in-center-and-move-map-around-it
