### ISSUE TITLE
+Post and +comment should be available always

### ISSUE THREAD

**Issue by khmak3** [OurLandHK/WebApp#248]
If user isn, t login,  we should redirect to sign in view.

**Comment by wingkwong** [comment]
where's sign in view? Currently, the only way to sign in is to click the Facebook button in Home page.

**Comment by khmak3** [comment]
We can make the Signin Button (Facebook button) has different view. It can look like +Post and +comment. If the user isn't login, we are showing the SiginButton with the look like +Post or +comment, :)
