### ISSUE TITLE
Update home page arrangement

### ISSUE THREAD

**Issue by khmak3** [OurLandHK/WebApp#370]
Message list at top
Focus news should show just above the message list

**Comment by khmak3** [comment]
click 我地市政要back to home

**Comment by wingkwong** [comment]
just above the message list?

If so, then the order would be:
1. FocusMessage
2. messageList
3. tagStatHtml
4. recentMessage

is it correct?

**Comment by khmak3** [comment]
1. tagStatHtml
2. recentMessage
3. messageList <- This should be capped for 3 or 4 entries to show.
4. FocusMessage

**Comment by wingkwong** [comment]
self-assigned
