### ISSUE TITLE
Parsing description and put location/date into message

### ISSUE THREAD

**Issue by khmak3** [OurLandHK/WebApp#382]
1. After user specified description of a message
2. Click 分析時間及地點
3. Use google API to parse the string after "地點"/"地點:"/"Place"/"venue"   
4. Use javascript date time API to parse the string after "日期"/"時間:"/"Date"/"Time"   

Use the first appear string.
For the location, need to check within Hong Kong

For thte Date, need to check that's in future
Date is more important than time

**Comment by wingkwong** [comment]
self-assigned

**Comment by wingkwong** [comment]
self-assigned
