### ISSUE TITLE
UI bugs in profile page

### ISSUE THREAD

**Issue by howawong** [OurLandHK/WebApp#85]
![img_4903](https://user-images.githubusercontent.com/760880/37337614-d1b6f11c-26ef-11e8-9350-1247ad2942ab.PNG)

1. Profile pic is missing
2. Save should be in chinese, not english
3. Clicking  "發表事件" should show another UI
4. Clicking  "完成事件" should show another UI
5. 輸入位置 should be a button or 輸入位置 might not be needed, as there is address book.

**Comment by khmak3** [comment]
Fix togther in #118
