### ISSUE TITLE
Back button should be overridden so that dialog is closed, but not going back to the previous page

### ISSUE THREAD

**Issue by howawong** [OurLandHK/WebApp#91]
https://youtu.be/aSA6G4vQ4kw

**Comment by khmak3** [comment]
https://zinoui.com/blog/single-page-apps-html5-pushstate

**Comment by khmak3** [comment]
Simpler solution for react js


  onBackButtonEvent: function (e) {
    debug('handling back button press')
    e.preventDefault()
    this.transitionTo('chatrooms')
  },

  componentDidMount: function() {
    window.onpopstate = this.onBackButtonEvent
  },
