### ISSUE TITLE
User can change on their profile picture

### ISSUE THREAD

**Issue by khmak3** [OurLandHK/WebApp#97]

**Comment by wingkwong** [comment]
I'm working on it.

**Comment by khmak3** [comment]
Thanks,  please use the uploadimagebutton.js to upload image.  The image should store under the photo storage under /photo/<uid>/profile#.jpg

**Comment by khmak3** [comment]
GIve me a facebook profile to add you into facebook. Message for discuss about develop plan

**Comment by wingkwong** [comment]
I've opened a pull request #117 for this issue.

For facebook profile, I've sent it to your personal email.
